### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by Ekliptor** [okcoin-okex/okex-api-v3-node-sdk#1]
Hi,
I want to integrate your API into my trading bot https://github.com/Ekliptor/WolfBot

Can you please provide some examples for buying/selling features and reading data from Websockets?
Thanks

**Comment by imhazige** [comment]
代码都写了，文档能不能提供下？怎么用啊？

**Comment by Ekliptor** [comment]
any update on this?

**Comment by BigXia** [comment]
有没有 demo 呢

**Comment by zisuting** [comment]
demo 地址
https://github.com/zisuting/okex-node-sdk-sample
