### ISSUE TITLE
[request] Websocket feed *subscribe all*

### ISSUE THREAD

**Issue by npomfret** [okcoin-okex/okex-api-v3-node-sdk#14]
I need to monitor all channels for a user (all orders, trades, accounts etc).  The only solution I can see is that I need to subscribe to hundreds of different channels when my app starts. 

Please can you add support for streaming all private data for a user in a *single* API call?

**Comment by zisuting** [comment]
you can use this method:
ws.subscribe('otc/order:*');
you can subscribe all order's data.
