### ISSUE TITLE
futures post leverage can not set as crossed margin mode

### ISSUE THREAD

**Issue by jhsea3do** [okcoin-okex/okex-api-v3-node-sdk#3]
i want set my ETH futures leverage to crossed margin mode, and 20x leverage.
then i run  

```javascript
const res = authClient.futures().postLeverage('ETH', { 'leverage': 20 });
```
it was failed and responed following messages:

```javascript
  axios POST /api/futures/v3/accounts/ETH/leverage +0ms
  axios Error: Request failed with status code 400 (POST https://www.okex.com/api/futures/v3/accounts/ETH/leverage) +2s
{
  "code": 30023,
  "message": "instrument_id cannot be blank"
}

```

and even still  error with 'margin_mode' attribute.
```javascript
const res = authClient.futures().postLeverage('ETH', { 'leverage': 20, 'margin_mode': 'crossed' });

const res = authClient.futures().postLeverage('ETH', '20');
```

maybe the problem occurred in server side ? 
below are from official api docs: 

```
Set Futures Leverage
Adjusting the leverage for futures account。

HTTP Requests
POST /api/futures/v3/accounts/<currency>/leverage

Limit: 5 times / 2s
Request Sample
POST/api/futures/v3/accounts/btc/leverage{"leverage":"10"} (Cross_margin)

POST/api/futures/v3/accounts/btc/leverage{"instrument_id":"BTC-USD-180213","direction":"long","leverage":"10"}（Fixed_margin）
```

**Comment by LikeTheWolf** [comment]
Best guess without looking into this is that "ETH" is not an instrument, try being more specific with your request. It seems like the product should have more information such as  (eg for bitcoin BTC-USD-180213)  --- is it future/spot? is it swap? USD/other currency? ETH most likely doesnt correspond to any instrument on the server so it is rendering to blank and then complaining about it. Hope this helps!

**Comment by jhsea3do** [comment]
@LikeTheWolf   

Thank you, it might be my mistake,  i shouldn't use currency symbol, 

I'll close this issue, but i don't have  time test it recently.
