### ISSUE TITLE
Error catching issue

### ISSUE THREAD

**Issue by Pizhevsky** [okcoin-okex/okex-api-v3-node-sdk#5]
Please fix the line 
"console.log(JSON.stringify(error.response.data));"
When "error" has no "response" - we have a problem... Real error is "timeout of 3000ms exceeded". By the way, can I change "timeout" parameter?

**Comment by zisuting** [comment]
"console.log(JSON.stringify(error.response.data));"
When "error" has no "response"---- this problem has been resloved,  the timeout parameter has been added to the interfaces.
