### ISSUE TITLE
错误处理

### ISSUE THREAD

**Issue by imhazige** [okcoin-okex/okex-api-v3-node-sdk#6]
没有错误处理吗？

没有异常抛出，只看到打印错误日志。

{"code":30006,"message":"Invalid OK-ACCESS-KEY"}
 /api/spot/v3/orders error

**Comment by zisuting** [comment]
目前是打印错误日志，不算异常

**Comment by imhazige** [comment]
错误要抛出来啊，比如错误的api key
为什么不算异常？
我测试时不能捕获异常，代码逻辑不能正常运行。

https://github.com/okcoin-okex/okex-api-v3-node-sdk/pulls

**Comment by zisuting** [comment]
更新到0.0.49 ,get, post 错误都会throw error ,你可以捕获这个异常做处理
