### ISSUE TITLE
How to use agent?

### ISSUE THREAD

**Issue by miaoihan** [okcoin-okex/okex-api-v3-node-sdk#8]
* **Question**
How can i use the ws agent like 
`ws = new WebSocket(wssUrl, { agent: Agent })`

**Comment by zisuting** [comment]
const HttpsProxyAgent = require('https-proxy-agent');
const proxy = 'http://127.0.0.1:1087';
const agent = new HttpsProxyAgent(proxy);
const event = new EventEmitter();
const wss = new V3WebsocketClient(config.websocekHost);
wss.connect({agent});
